### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by e-jigsaw** [iojs-jp/blog#7]

**Comment by yosuke-furukawa** [comment]
![http://blog.iojs.jp/logo.png](http://blog.iojs.jp/logo.png)
これでいいのでは？

**Comment by e-jigsaw** [comment]
はい、その画像を変換してソースにいれればいいやーとおもいつつ手つけてなかったやつです...

https://github.com/iojs/iojs-ja/pull/42 のついでぐらいで対応しますね
